version: '3'
services:

  postgres:
      build:
        context: .
        dockerfile: postgres.dockerfile
      container_name: ddd-southwest-database
      image: postgres:9.4
      restart: always
      # volumes:
      #   - ./postgres-data:/var/lib/postgresql/data
      environment:
        - POSTGRES_USER=dddsouthwest_user
        - POSTGRES_PASSWORD=letmein
        - POSTGRES_DB=dddsouthwest
      ports:
        - "5432:5432"